//
//  MovieTuesdayGoodModel.m
//
//  Created by MACIO 猫爷 on 15/12/7
//  Copyright (c) 2015 __MyCompanyName__. All rights reserved.
//

#import "MovieTuesdayGoodModel.h"
#import "Attributes.h"


NSString *const kMovieTuesdayGoodModelReturnMoney = @"return_money";
NSString *const kMovieTuesdayGoodModelPublishWait = @"publish_wait";
NSString *const kMovieTuesdayGoodModelDescription = @"description";
NSString *const kMovieTuesdayGoodModelIcon = @"icon";
NSString *const kMovieTuesdayGoodModelSubName = @"sub_name";
NSString *const kMovieTuesdayGoodModelMobilePhone = @"mobile_phone";
NSString *const kMovieTuesdayGoodModelBuyCount = @"buy_count";
NSString *const kMovieTuesdayGoodModelTagMatch = @"tag_match";
NSString *const kMovieTuesdayGoodModelId = @"id";
NSString *const kMovieTuesdayGoodModelWeight = @"weight";
NSString *const kMovieTuesdayGoodModelDealGoodsType = @"deal_goods_type";
NSString *const kMovieTuesdayGoodModelIsNew = @"is_new";
NSString *const kMovieTuesdayGoodModelBalancePrice = @"balance_price";
NSString *const kMovieTuesdayGoodModelShopCateMatch = @"shop_cate_match";
NSString *const kMovieTuesdayGoodModelShopCateId = @"shop_cate_id";
NSString *const kMovieTuesdayGoodModelDefinePayment = @"define_payment";
NSString *const kMovieTuesdayGoodModelSort = @"sort";
NSString *const kMovieTuesdayGoodModelOnSale = @"on_sale";
NSString *const kMovieTuesdayGoodModelNotice = @"notice";
NSString *const kMovieTuesdayGoodModelCode = @"code";
NSString *const kMovieTuesdayGoodModelAutoOrder = @"auto_order";
NSString *const kMovieTuesdayGoodModelDiscuss = @"discuss";
NSString *const kMovieTuesdayGoodModelCouponBeginTime = @"coupon_begin_time";
NSString *const kMovieTuesdayGoodModelForbidSms = @"forbid_sms";
NSString *const kMovieTuesdayGoodModelIsHot = @"is_hot";
NSString *const kMovieTuesdayGoodModelIsDeposit = @"is_deposit";
NSString *const kMovieTuesdayGoodModelUserMaxBought = @"user_max_bought";
NSString *const kMovieTuesdayGoodModelIsDelivery = @"is_delivery";
NSString *const kMovieTuesdayGoodModelSales = @"sales";
NSString *const kMovieTuesdayGoodModelName = @"name";
NSString *const kMovieTuesdayGoodModelNameMatchRow = @"name_match_row";
NSString *const kMovieTuesdayGoodModelIsCoupon = @"is_coupon";
NSString *const kMovieTuesdayGoodModelUserMinBought = @"user_min_bought";
NSString *const kMovieTuesdayGoodModelLocateMatchRow = @"locate_match_row";
NSString *const kMovieTuesdayGoodModelCateId = @"cate_id";
NSString *const kMovieTuesdayGoodModelCartType = @"cart_type";
NSString *const kMovieTuesdayGoodModelShopCateMatchRow = @"shop_cate_match_row";
NSString *const kMovieTuesdayGoodModelReopen = @"reopen";
NSString *const kMovieTuesdayGoodModelIsDelete = @"is_delete";
NSString *const kMovieTuesdayGoodModelIsLottery = @"is_lottery";
NSString *const kMovieTuesdayGoodModelSuccessTime = @"success_time";
NSString *const kMovieTuesdayGoodModelExpireRefund = @"expire_refund";
NSString *const kMovieTuesdayGoodModelSeoKeyword = @"seo_keyword";
NSString *const kMovieTuesdayGoodModelIsRefund = @"is_refund";
NSString *const kMovieTuesdayGoodModelDealType = @"deal_type";
NSString *const kMovieTuesdayGoodModelIsHome = @"is_home";
NSString *const kMovieTuesdayGoodModelAllowPromote = @"allow_promote";
NSString *const kMovieTuesdayGoodModelCreateTime = @"create_time";
NSString *const kMovieTuesdayGoodModelBeginTime = @"begin_time";
NSString *const kMovieTuesdayGoodModelUpdateTime = @"update_time";
NSString *const kMovieTuesdayGoodModelTimeStatus = @"time_status";
NSString *const kMovieTuesdayGoodModelReturnScore = @"return_score";
NSString *const kMovieTuesdayGoodModelDealCateMatchRow = @"deal_cate_match_row";
NSString *const kMovieTuesdayGoodModelDiscount = @"discount";
NSString *const kMovieTuesdayGoodModelSeoTitle = @"seo_title";
NSString *const kMovieTuesdayGoodModelTagMatchRow = @"tag_match_row";
NSString *const kMovieTuesdayGoodModelBuyType = @"buy_type";
NSString *const kMovieTuesdayGoodModelIsShop = @"is_shop";
NSString *const kMovieTuesdayGoodModelImgs = @"imgs";
NSString *const kMovieTuesdayGoodModelAccountId = @"account_id";
NSString *const kMovieTuesdayGoodModelImg = @"img";
NSString *const kMovieTuesdayGoodModelUname = @"uname";
NSString *const kMovieTuesdayGoodModelBuyStatus = @"buy_status";
NSString *const kMovieTuesdayGoodModelCityId = @"city_id";
NSString *const kMovieTuesdayGoodModelBrandId = @"brand_id";
NSString *const kMovieTuesdayGoodModelIsEffect = @"is_effect";
NSString *const kMovieTuesdayGoodModelLocationId = @"location_id";
NSString *const kMovieTuesdayGoodModelUserCount = @"user_count";
NSString *const kMovieTuesdayGoodModelYpoint = @"ypoint";
NSString *const kMovieTuesdayGoodModelBrief = @"brief";
NSString *const kMovieTuesdayGoodModelOriginPrice = @"origin_price";
NSString *const kMovieTuesdayGoodModelMinBought = @"min_bought";
NSString *const kMovieTuesdayGoodModelIsReferral = @"is_referral";
NSString *const kMovieTuesdayGoodModelIsBest = @"is_best";
NSString *const kMovieTuesdayGoodModelDeliveryId = @"delivery_id";
NSString *const kMovieTuesdayGoodModelAvgPoint = @"avg_point";
NSString *const kMovieTuesdayGoodModelAttributes = @"attributes";
NSString *const kMovieTuesdayGoodModelLocationDealTypeId = @"location_deal_type_id";
NSString *const kMovieTuesdayGoodModelEndTime = @"end_time";
NSString *const kMovieTuesdayGoodModelTotalPoint = @"total_point";
NSString *const kMovieTuesdayGoodModelWeightId = @"weight_id";
NSString *const kMovieTuesdayGoodModelCurrentPrice = @"current_price";
NSString *const kMovieTuesdayGoodModelMaxBought = @"max_bought";
NSString *const kMovieTuesdayGoodModelSupplierId = @"supplier_id";
NSString *const kMovieTuesdayGoodModelFeature = @"feature";
NSString *const kMovieTuesdayGoodModelLocateMatch = @"locate_match";
NSString *const kMovieTuesdayGoodModelAcreage = @"acreage";
NSString *const kMovieTuesdayGoodModelTime = @"time";
NSString *const kMovieTuesdayGoodModelCouponEndTime = @"coupon_end_time";
NSString *const kMovieTuesdayGoodModelFreeDelivery = @"free_delivery";
NSString *const kMovieTuesdayGoodModelAnyRefund = @"any_refund";
NSString *const kMovieTuesdayGoodModelXpoint = @"xpoint";
NSString *const kMovieTuesdayGoodModelSeoDescription = @"seo_description";
NSString *const kMovieTuesdayGoodModelNameMatch = @"name_match";
NSString *const kMovieTuesdayGoodModelIsRecommend = @"is_recommend";
NSString *const kMovieTuesdayGoodModelDepositPrice = @"deposit_price";
NSString *const kMovieTuesdayGoodModelDealCateMatch = @"deal_cate_match";
NSString *const kMovieTuesdayGoodModelMultiAttr = @"multi_attr";
NSString *const kMovieTuesdayGoodModelBrandPromote = @"brand_promote";


@interface MovieTuesdayGoodModel ()

- (id)objectOrNilForKey:(id)aKey fromDictionary:(NSDictionary *)dict;

@end

@implementation MovieTuesdayGoodModel

@synthesize returnMoney = _returnMoney;
@synthesize publishWait = _publishWait;
@synthesize movieTuesdayGoodModelDescription = _movieTuesdayGoodModelDescription;
@synthesize icon = _icon;
@synthesize subName = _subName;
@synthesize mobilePhone = _mobilePhone;
@synthesize buyCount = _buyCount;
@synthesize tagMatch = _tagMatch;
@synthesize movieTuesdayGoodModelIdentifier = _movieTuesdayGoodModelIdentifier;
@synthesize weight = _weight;
@synthesize dealGoodsType = _dealGoodsType;
@synthesize isNew = _isNew;
@synthesize balancePrice = _balancePrice;
@synthesize shopCateMatch = _shopCateMatch;
@synthesize shopCateId = _shopCateId;
@synthesize definePayment = _definePayment;
@synthesize sort = _sort;
@synthesize onSale = _onSale;
@synthesize notice = _notice;
@synthesize code = _code;
@synthesize autoOrder = _autoOrder;
@synthesize discuss = _discuss;
@synthesize couponBeginTime = _couponBeginTime;
@synthesize forbidSms = _forbidSms;
@synthesize isHot = _isHot;
@synthesize isDeposit = _isDeposit;
@synthesize userMaxBought = _userMaxBought;
@synthesize isDelivery = _isDelivery;
@synthesize sales = _sales;
@synthesize name = _name;
@synthesize nameMatchRow = _nameMatchRow;
@synthesize isCoupon = _isCoupon;
@synthesize userMinBought = _userMinBought;
@synthesize locateMatchRow = _locateMatchRow;
@synthesize cateId = _cateId;
@synthesize cartType = _cartType;
@synthesize shopCateMatchRow = _shopCateMatchRow;
@synthesize reopen = _reopen;
@synthesize isDelete = _isDelete;
@synthesize isLottery = _isLottery;
@synthesize successTime = _successTime;
@synthesize expireRefund = _expireRefund;
@synthesize seoKeyword = _seoKeyword;
@synthesize isRefund = _isRefund;
@synthesize dealType = _dealType;
@synthesize isHome = _isHome;
@synthesize allowPromote = _allowPromote;
@synthesize createTime = _createTime;
@synthesize beginTime = _beginTime;
@synthesize updateTime = _updateTime;
@synthesize timeStatus = _timeStatus;
@synthesize returnScore = _returnScore;
@synthesize dealCateMatchRow = _dealCateMatchRow;
@synthesize discount = _discount;
@synthesize seoTitle = _seoTitle;
@synthesize tagMatchRow = _tagMatchRow;
@synthesize buyType = _buyType;
@synthesize isShop = _isShop;
@synthesize imgs = _imgs;
@synthesize accountId = _accountId;
@synthesize img = _img;
@synthesize uname = _uname;
@synthesize buyStatus = _buyStatus;
@synthesize cityId = _cityId;
@synthesize brandId = _brandId;
@synthesize isEffect = _isEffect;
@synthesize locationId = _locationId;
@synthesize userCount = _userCount;
@synthesize ypoint = _ypoint;
@synthesize brief = _brief;
@synthesize originPrice = _originPrice;
@synthesize minBought = _minBought;
@synthesize isReferral = _isReferral;
@synthesize isBest = _isBest;
@synthesize deliveryId = _deliveryId;
@synthesize avgPoint = _avgPoint;
@synthesize attributes = _attributes;
@synthesize locationDealTypeId = _locationDealTypeId;
@synthesize endTime = _endTime;
@synthesize totalPoint = _totalPoint;
@synthesize weightId = _weightId;
@synthesize currentPrice = _currentPrice;
@synthesize maxBought = _maxBought;
@synthesize supplierId = _supplierId;
@synthesize feature = _feature;
@synthesize locateMatch = _locateMatch;
@synthesize acreage = _acreage;
@synthesize time = _time;
@synthesize couponEndTime = _couponEndTime;
@synthesize freeDelivery = _freeDelivery;
@synthesize anyRefund = _anyRefund;
@synthesize xpoint = _xpoint;
@synthesize seoDescription = _seoDescription;
@synthesize nameMatch = _nameMatch;
@synthesize isRecommend = _isRecommend;
@synthesize depositPrice = _depositPrice;
@synthesize dealCateMatch = _dealCateMatch;
@synthesize multiAttr = _multiAttr;
@synthesize brandPromote = _brandPromote;


+ (instancetype)modelObjectWithDictionary:(NSDictionary *)dict
{
    return [[self alloc] initWithDictionary:dict];
}

- (instancetype)initWithDictionary:(NSDictionary *)dict
{
    self = [super init];
    
    // This check serves to make sure that a non-NSDictionary object
    // passed into the model class doesn't break the parsing.
    if(self && [dict isKindOfClass:[NSDictionary class]]) {
            self.returnMoney = [self objectOrNilForKey:kMovieTuesdayGoodModelReturnMoney fromDictionary:dict];
            self.publishWait = [self objectOrNilForKey:kMovieTuesdayGoodModelPublishWait fromDictionary:dict];
            self.movieTuesdayGoodModelDescription = [self objectOrNilForKey:kMovieTuesdayGoodModelDescription fromDictionary:dict];
            self.icon = [self objectOrNilForKey:kMovieTuesdayGoodModelIcon fromDictionary:dict];
            self.subName = [self objectOrNilForKey:kMovieTuesdayGoodModelSubName fromDictionary:dict];
            self.mobilePhone = [self objectOrNilForKey:kMovieTuesdayGoodModelMobilePhone fromDictionary:dict];
            self.buyCount = [self objectOrNilForKey:kMovieTuesdayGoodModelBuyCount fromDictionary:dict];
            self.tagMatch = [self objectOrNilForKey:kMovieTuesdayGoodModelTagMatch fromDictionary:dict];
            self.movieTuesdayGoodModelIdentifier = [self objectOrNilForKey:kMovieTuesdayGoodModelId fromDictionary:dict];
            self.weight = [self objectOrNilForKey:kMovieTuesdayGoodModelWeight fromDictionary:dict];
            self.dealGoodsType = [self objectOrNilForKey:kMovieTuesdayGoodModelDealGoodsType fromDictionary:dict];
            self.isNew = [self objectOrNilForKey:kMovieTuesdayGoodModelIsNew fromDictionary:dict];
            self.balancePrice = [self objectOrNilForKey:kMovieTuesdayGoodModelBalancePrice fromDictionary:dict];
            self.shopCateMatch = [self objectOrNilForKey:kMovieTuesdayGoodModelShopCateMatch fromDictionary:dict];
            self.shopCateId = [self objectOrNilForKey:kMovieTuesdayGoodModelShopCateId fromDictionary:dict];
            self.definePayment = [self objectOrNilForKey:kMovieTuesdayGoodModelDefinePayment fromDictionary:dict];
            self.sort = [self objectOrNilForKey:kMovieTuesdayGoodModelSort fromDictionary:dict];
            self.onSale = [self objectOrNilForKey:kMovieTuesdayGoodModelOnSale fromDictionary:dict];
            self.notice = [self objectOrNilForKey:kMovieTuesdayGoodModelNotice fromDictionary:dict];
            self.code = [self objectOrNilForKey:kMovieTuesdayGoodModelCode fromDictionary:dict];
            self.autoOrder = [self objectOrNilForKey:kMovieTuesdayGoodModelAutoOrder fromDictionary:dict];
            self.discuss = [self objectOrNilForKey:kMovieTuesdayGoodModelDiscuss fromDictionary:dict];
            self.couponBeginTime = [self objectOrNilForKey:kMovieTuesdayGoodModelCouponBeginTime fromDictionary:dict];
            self.forbidSms = [self objectOrNilForKey:kMovieTuesdayGoodModelForbidSms fromDictionary:dict];
            self.isHot = [self objectOrNilForKey:kMovieTuesdayGoodModelIsHot fromDictionary:dict];
            self.isDeposit = [self objectOrNilForKey:kMovieTuesdayGoodModelIsDeposit fromDictionary:dict];
            self.userMaxBought = [self objectOrNilForKey:kMovieTuesdayGoodModelUserMaxBought fromDictionary:dict];
            self.isDelivery = [self objectOrNilForKey:kMovieTuesdayGoodModelIsDelivery fromDictionary:dict];
            self.sales = [self objectOrNilForKey:kMovieTuesdayGoodModelSales fromDictionary:dict];
            self.name = [self objectOrNilForKey:kMovieTuesdayGoodModelName fromDictionary:dict];
            self.nameMatchRow = [self objectOrNilForKey:kMovieTuesdayGoodModelNameMatchRow fromDictionary:dict];
            self.isCoupon = [self objectOrNilForKey:kMovieTuesdayGoodModelIsCoupon fromDictionary:dict];
            self.userMinBought = [self objectOrNilForKey:kMovieTuesdayGoodModelUserMinBought fromDictionary:dict];
            self.locateMatchRow = [self objectOrNilForKey:kMovieTuesdayGoodModelLocateMatchRow fromDictionary:dict];
            self.cateId = [self objectOrNilForKey:kMovieTuesdayGoodModelCateId fromDictionary:dict];
            self.cartType = [self objectOrNilForKey:kMovieTuesdayGoodModelCartType fromDictionary:dict];
            self.shopCateMatchRow = [self objectOrNilForKey:kMovieTuesdayGoodModelShopCateMatchRow fromDictionary:dict];
            self.reopen = [self objectOrNilForKey:kMovieTuesdayGoodModelReopen fromDictionary:dict];
            self.isDelete = [self objectOrNilForKey:kMovieTuesdayGoodModelIsDelete fromDictionary:dict];
            self.isLottery = [self objectOrNilForKey:kMovieTuesdayGoodModelIsLottery fromDictionary:dict];
            self.successTime = [self objectOrNilForKey:kMovieTuesdayGoodModelSuccessTime fromDictionary:dict];
            self.expireRefund = [self objectOrNilForKey:kMovieTuesdayGoodModelExpireRefund fromDictionary:dict];
            self.seoKeyword = [self objectOrNilForKey:kMovieTuesdayGoodModelSeoKeyword fromDictionary:dict];
            self.isRefund = [self objectOrNilForKey:kMovieTuesdayGoodModelIsRefund fromDictionary:dict];
            self.dealType = [self objectOrNilForKey:kMovieTuesdayGoodModelDealType fromDictionary:dict];
            self.isHome = [self objectOrNilForKey:kMovieTuesdayGoodModelIsHome fromDictionary:dict];
            self.allowPromote = [self objectOrNilForKey:kMovieTuesdayGoodModelAllowPromote fromDictionary:dict];
            self.createTime = [self objectOrNilForKey:kMovieTuesdayGoodModelCreateTime fromDictionary:dict];
            self.beginTime = [self objectOrNilForKey:kMovieTuesdayGoodModelBeginTime fromDictionary:dict];
            self.updateTime = [self objectOrNilForKey:kMovieTuesdayGoodModelUpdateTime fromDictionary:dict];
            self.timeStatus = [self objectOrNilForKey:kMovieTuesdayGoodModelTimeStatus fromDictionary:dict];
            self.returnScore = [self objectOrNilForKey:kMovieTuesdayGoodModelReturnScore fromDictionary:dict];
            self.dealCateMatchRow = [self objectOrNilForKey:kMovieTuesdayGoodModelDealCateMatchRow fromDictionary:dict];
            self.discount = [self objectOrNilForKey:kMovieTuesdayGoodModelDiscount fromDictionary:dict];
            self.seoTitle = [self objectOrNilForKey:kMovieTuesdayGoodModelSeoTitle fromDictionary:dict];
            self.tagMatchRow = [self objectOrNilForKey:kMovieTuesdayGoodModelTagMatchRow fromDictionary:dict];
            self.buyType = [self objectOrNilForKey:kMovieTuesdayGoodModelBuyType fromDictionary:dict];
            self.isShop = [self objectOrNilForKey:kMovieTuesdayGoodModelIsShop fromDictionary:dict];
            self.imgs = [self objectOrNilForKey:kMovieTuesdayGoodModelImgs fromDictionary:dict];
            self.accountId = [self objectOrNilForKey:kMovieTuesdayGoodModelAccountId fromDictionary:dict];
            self.img = [self objectOrNilForKey:kMovieTuesdayGoodModelImg fromDictionary:dict];
            self.uname = [self objectOrNilForKey:kMovieTuesdayGoodModelUname fromDictionary:dict];
            self.buyStatus = [self objectOrNilForKey:kMovieTuesdayGoodModelBuyStatus fromDictionary:dict];
            self.cityId = [self objectOrNilForKey:kMovieTuesdayGoodModelCityId fromDictionary:dict];
            self.brandId = [self objectOrNilForKey:kMovieTuesdayGoodModelBrandId fromDictionary:dict];
            self.isEffect = [self objectOrNilForKey:kMovieTuesdayGoodModelIsEffect fromDictionary:dict];
            self.locationId = [self objectOrNilForKey:kMovieTuesdayGoodModelLocationId fromDictionary:dict];
            self.userCount = [self objectOrNilForKey:kMovieTuesdayGoodModelUserCount fromDictionary:dict];
            self.ypoint = [self objectOrNilForKey:kMovieTuesdayGoodModelYpoint fromDictionary:dict];
            self.brief = [self objectOrNilForKey:kMovieTuesdayGoodModelBrief fromDictionary:dict];
            self.originPrice = [self objectOrNilForKey:kMovieTuesdayGoodModelOriginPrice fromDictionary:dict];
            self.minBought = [self objectOrNilForKey:kMovieTuesdayGoodModelMinBought fromDictionary:dict];
            self.isReferral = [self objectOrNilForKey:kMovieTuesdayGoodModelIsReferral fromDictionary:dict];
            self.isBest = [self objectOrNilForKey:kMovieTuesdayGoodModelIsBest fromDictionary:dict];
            self.deliveryId = [self objectOrNilForKey:kMovieTuesdayGoodModelDeliveryId fromDictionary:dict];
            self.avgPoint = [self objectOrNilForKey:kMovieTuesdayGoodModelAvgPoint fromDictionary:dict];
            self.attributes = [Attributes modelObjectWithDictionary:[dict objectForKey:kMovieTuesdayGoodModelAttributes]];
            self.locationDealTypeId = [self objectOrNilForKey:kMovieTuesdayGoodModelLocationDealTypeId fromDictionary:dict];
            self.endTime = [self objectOrNilForKey:kMovieTuesdayGoodModelEndTime fromDictionary:dict];
            self.totalPoint = [self objectOrNilForKey:kMovieTuesdayGoodModelTotalPoint fromDictionary:dict];
            self.weightId = [self objectOrNilForKey:kMovieTuesdayGoodModelWeightId fromDictionary:dict];
            self.currentPrice = [self objectOrNilForKey:kMovieTuesdayGoodModelCurrentPrice fromDictionary:dict];
            self.maxBought = [self objectOrNilForKey:kMovieTuesdayGoodModelMaxBought fromDictionary:dict];
            self.supplierId = [self objectOrNilForKey:kMovieTuesdayGoodModelSupplierId fromDictionary:dict];
            self.feature = [self objectOrNilForKey:kMovieTuesdayGoodModelFeature fromDictionary:dict];
            self.locateMatch = [self objectOrNilForKey:kMovieTuesdayGoodModelLocateMatch fromDictionary:dict];
            self.acreage = [self objectOrNilForKey:kMovieTuesdayGoodModelAcreage fromDictionary:dict];
            self.time = [self objectOrNilForKey:kMovieTuesdayGoodModelTime fromDictionary:dict];
            self.couponEndTime = [self objectOrNilForKey:kMovieTuesdayGoodModelCouponEndTime fromDictionary:dict];
            self.freeDelivery = [self objectOrNilForKey:kMovieTuesdayGoodModelFreeDelivery fromDictionary:dict];
            self.anyRefund = [self objectOrNilForKey:kMovieTuesdayGoodModelAnyRefund fromDictionary:dict];
            self.xpoint = [self objectOrNilForKey:kMovieTuesdayGoodModelXpoint fromDictionary:dict];
            self.seoDescription = [self objectOrNilForKey:kMovieTuesdayGoodModelSeoDescription fromDictionary:dict];
            self.nameMatch = [self objectOrNilForKey:kMovieTuesdayGoodModelNameMatch fromDictionary:dict];
            self.isRecommend = [self objectOrNilForKey:kMovieTuesdayGoodModelIsRecommend fromDictionary:dict];
            self.depositPrice = [self objectOrNilForKey:kMovieTuesdayGoodModelDepositPrice fromDictionary:dict];
            self.dealCateMatch = [self objectOrNilForKey:kMovieTuesdayGoodModelDealCateMatch fromDictionary:dict];
            self.multiAttr = [self objectOrNilForKey:kMovieTuesdayGoodModelMultiAttr fromDictionary:dict];
            self.brandPromote = [self objectOrNilForKey:kMovieTuesdayGoodModelBrandPromote fromDictionary:dict];

    }
    
    return self;
    
}

- (NSDictionary *)dictionaryRepresentation
{
    NSMutableDictionary *mutableDict = [NSMutableDictionary dictionary];
    [mutableDict setValue:self.returnMoney forKey:kMovieTuesdayGoodModelReturnMoney];
    [mutableDict setValue:self.publishWait forKey:kMovieTuesdayGoodModelPublishWait];
    [mutableDict setValue:self.movieTuesdayGoodModelDescription forKey:kMovieTuesdayGoodModelDescription];
    [mutableDict setValue:self.icon forKey:kMovieTuesdayGoodModelIcon];
    [mutableDict setValue:self.subName forKey:kMovieTuesdayGoodModelSubName];
    [mutableDict setValue:self.mobilePhone forKey:kMovieTuesdayGoodModelMobilePhone];
    [mutableDict setValue:self.buyCount forKey:kMovieTuesdayGoodModelBuyCount];
    [mutableDict setValue:self.tagMatch forKey:kMovieTuesdayGoodModelTagMatch];
    [mutableDict setValue:self.movieTuesdayGoodModelIdentifier forKey:kMovieTuesdayGoodModelId];
    [mutableDict setValue:self.weight forKey:kMovieTuesdayGoodModelWeight];
    [mutableDict setValue:self.dealGoodsType forKey:kMovieTuesdayGoodModelDealGoodsType];
    [mutableDict setValue:self.isNew forKey:kMovieTuesdayGoodModelIsNew];
    [mutableDict setValue:self.balancePrice forKey:kMovieTuesdayGoodModelBalancePrice];
    [mutableDict setValue:self.shopCateMatch forKey:kMovieTuesdayGoodModelShopCateMatch];
    [mutableDict setValue:self.shopCateId forKey:kMovieTuesdayGoodModelShopCateId];
    [mutableDict setValue:self.definePayment forKey:kMovieTuesdayGoodModelDefinePayment];
    [mutableDict setValue:self.sort forKey:kMovieTuesdayGoodModelSort];
    [mutableDict setValue:self.onSale forKey:kMovieTuesdayGoodModelOnSale];
    [mutableDict setValue:self.notice forKey:kMovieTuesdayGoodModelNotice];
    [mutableDict setValue:self.code forKey:kMovieTuesdayGoodModelCode];
    [mutableDict setValue:self.autoOrder forKey:kMovieTuesdayGoodModelAutoOrder];
    [mutableDict setValue:[NSNumber numberWithBool:self.discuss] forKey:kMovieTuesdayGoodModelDiscuss];
    [mutableDict setValue:self.couponBeginTime forKey:kMovieTuesdayGoodModelCouponBeginTime];
    [mutableDict setValue:self.forbidSms forKey:kMovieTuesdayGoodModelForbidSms];
    [mutableDict setValue:self.isHot forKey:kMovieTuesdayGoodModelIsHot];
    [mutableDict setValue:self.isDeposit forKey:kMovieTuesdayGoodModelIsDeposit];
    [mutableDict setValue:self.userMaxBought forKey:kMovieTuesdayGoodModelUserMaxBought];
    [mutableDict setValue:self.isDelivery forKey:kMovieTuesdayGoodModelIsDelivery];
    [mutableDict setValue:self.sales forKey:kMovieTuesdayGoodModelSales];
    [mutableDict setValue:self.name forKey:kMovieTuesdayGoodModelName];
    [mutableDict setValue:self.nameMatchRow forKey:kMovieTuesdayGoodModelNameMatchRow];
    [mutableDict setValue:self.isCoupon forKey:kMovieTuesdayGoodModelIsCoupon];
    [mutableDict setValue:self.userMinBought forKey:kMovieTuesdayGoodModelUserMinBought];
    [mutableDict setValue:self.locateMatchRow forKey:kMovieTuesdayGoodModelLocateMatchRow];
    [mutableDict setValue:self.cateId forKey:kMovieTuesdayGoodModelCateId];
    [mutableDict setValue:self.cartType forKey:kMovieTuesdayGoodModelCartType];
    [mutableDict setValue:self.shopCateMatchRow forKey:kMovieTuesdayGoodModelShopCateMatchRow];
    [mutableDict setValue:self.reopen forKey:kMovieTuesdayGoodModelReopen];
    [mutableDict setValue:self.isDelete forKey:kMovieTuesdayGoodModelIsDelete];
    [mutableDict setValue:self.isLottery forKey:kMovieTuesdayGoodModelIsLottery];
    [mutableDict setValue:self.successTime forKey:kMovieTuesdayGoodModelSuccessTime];
    [mutableDict setValue:self.expireRefund forKey:kMovieTuesdayGoodModelExpireRefund];
    [mutableDict setValue:self.seoKeyword forKey:kMovieTuesdayGoodModelSeoKeyword];
    [mutableDict setValue:self.isRefund forKey:kMovieTuesdayGoodModelIsRefund];
    [mutableDict setValue:self.dealType forKey:kMovieTuesdayGoodModelDealType];
    [mutableDict setValue:self.isHome forKey:kMovieTuesdayGoodModelIsHome];
    [mutableDict setValue:self.allowPromote forKey:kMovieTuesdayGoodModelAllowPromote];
    [mutableDict setValue:self.createTime forKey:kMovieTuesdayGoodModelCreateTime];
    [mutableDict setValue:self.beginTime forKey:kMovieTuesdayGoodModelBeginTime];
    [mutableDict setValue:self.updateTime forKey:kMovieTuesdayGoodModelUpdateTime];
    [mutableDict setValue:self.timeStatus forKey:kMovieTuesdayGoodModelTimeStatus];
    [mutableDict setValue:self.returnScore forKey:kMovieTuesdayGoodModelReturnScore];
    [mutableDict setValue:self.dealCateMatchRow forKey:kMovieTuesdayGoodModelDealCateMatchRow];
    [mutableDict setValue:self.discount forKey:kMovieTuesdayGoodModelDiscount];
    [mutableDict setValue:self.seoTitle forKey:kMovieTuesdayGoodModelSeoTitle];
    [mutableDict setValue:self.tagMatchRow forKey:kMovieTuesdayGoodModelTagMatchRow];
    [mutableDict setValue:self.buyType forKey:kMovieTuesdayGoodModelBuyType];
    [mutableDict setValue:self.isShop forKey:kMovieTuesdayGoodModelIsShop];
    [mutableDict setValue:[NSNumber numberWithBool:self.imgs] forKey:kMovieTuesdayGoodModelImgs];
    [mutableDict setValue:self.accountId forKey:kMovieTuesdayGoodModelAccountId];
    [mutableDict setValue:self.img forKey:kMovieTuesdayGoodModelImg];
    [mutableDict setValue:self.uname forKey:kMovieTuesdayGoodModelUname];
    [mutableDict setValue:self.buyStatus forKey:kMovieTuesdayGoodModelBuyStatus];
    [mutableDict setValue:self.cityId forKey:kMovieTuesdayGoodModelCityId];
    [mutableDict setValue:self.brandId forKey:kMovieTuesdayGoodModelBrandId];
    [mutableDict setValue:self.isEffect forKey:kMovieTuesdayGoodModelIsEffect];
    [mutableDict setValue:self.locationId forKey:kMovieTuesdayGoodModelLocationId];
    [mutableDict setValue:self.userCount forKey:kMovieTuesdayGoodModelUserCount];
    [mutableDict setValue:self.ypoint forKey:kMovieTuesdayGoodModelYpoint];
    [mutableDict setValue:self.brief forKey:kMovieTuesdayGoodModelBrief];
    [mutableDict setValue:self.originPrice forKey:kMovieTuesdayGoodModelOriginPrice];
    [mutableDict setValue:self.minBought forKey:kMovieTuesdayGoodModelMinBought];
    [mutableDict setValue:self.isReferral forKey:kMovieTuesdayGoodModelIsReferral];
    [mutableDict setValue:self.isBest forKey:kMovieTuesdayGoodModelIsBest];
    [mutableDict setValue:self.deliveryId forKey:kMovieTuesdayGoodModelDeliveryId];
    [mutableDict setValue:self.avgPoint forKey:kMovieTuesdayGoodModelAvgPoint];
    [mutableDict setValue:[self.attributes dictionaryRepresentation] forKey:kMovieTuesdayGoodModelAttributes];
    [mutableDict setValue:self.locationDealTypeId forKey:kMovieTuesdayGoodModelLocationDealTypeId];
    [mutableDict setValue:self.endTime forKey:kMovieTuesdayGoodModelEndTime];
    [mutableDict setValue:self.totalPoint forKey:kMovieTuesdayGoodModelTotalPoint];
    [mutableDict setValue:self.weightId forKey:kMovieTuesdayGoodModelWeightId];
    [mutableDict setValue:self.currentPrice forKey:kMovieTuesdayGoodModelCurrentPrice];
    [mutableDict setValue:self.maxBought forKey:kMovieTuesdayGoodModelMaxBought];
    [mutableDict setValue:self.supplierId forKey:kMovieTuesdayGoodModelSupplierId];
    [mutableDict setValue:self.feature forKey:kMovieTuesdayGoodModelFeature];
    [mutableDict setValue:self.locateMatch forKey:kMovieTuesdayGoodModelLocateMatch];
    [mutableDict setValue:self.acreage forKey:kMovieTuesdayGoodModelAcreage];
    [mutableDict setValue:self.time forKey:kMovieTuesdayGoodModelTime];
    [mutableDict setValue:self.couponEndTime forKey:kMovieTuesdayGoodModelCouponEndTime];
    [mutableDict setValue:self.freeDelivery forKey:kMovieTuesdayGoodModelFreeDelivery];
    [mutableDict setValue:self.anyRefund forKey:kMovieTuesdayGoodModelAnyRefund];
    [mutableDict setValue:self.xpoint forKey:kMovieTuesdayGoodModelXpoint];
    [mutableDict setValue:self.seoDescription forKey:kMovieTuesdayGoodModelSeoDescription];
    [mutableDict setValue:self.nameMatch forKey:kMovieTuesdayGoodModelNameMatch];
    [mutableDict setValue:self.isRecommend forKey:kMovieTuesdayGoodModelIsRecommend];
    [mutableDict setValue:self.depositPrice forKey:kMovieTuesdayGoodModelDepositPrice];
    [mutableDict setValue:self.dealCateMatch forKey:kMovieTuesdayGoodModelDealCateMatch];
    [mutableDict setValue:self.multiAttr forKey:kMovieTuesdayGoodModelMultiAttr];
    [mutableDict setValue:self.brandPromote forKey:kMovieTuesdayGoodModelBrandPromote];

    return [NSDictionary dictionaryWithDictionary:mutableDict];
}

- (NSString *)description 
{
    return [NSString stringWithFormat:@"%@", [self dictionaryRepresentation]];
}

#pragma mark - Helper Method
- (id)objectOrNilForKey:(id)aKey fromDictionary:(NSDictionary *)dict
{
    id object = [dict objectForKey:aKey];
    return [object isEqual:[NSNull null]] ? nil : object;
}


#pragma mark - NSCoding Methods

- (id)initWithCoder:(NSCoder *)aDecoder
{
    self = [super init];

    self.returnMoney = [aDecoder decodeObjectForKey:kMovieTuesdayGoodModelReturnMoney];
    self.publishWait = [aDecoder decodeObjectForKey:kMovieTuesdayGoodModelPublishWait];
    self.movieTuesdayGoodModelDescription = [aDecoder decodeObjectForKey:kMovieTuesdayGoodModelDescription];
    self.icon = [aDecoder decodeObjectForKey:kMovieTuesdayGoodModelIcon];
    self.subName = [aDecoder decodeObjectForKey:kMovieTuesdayGoodModelSubName];
    self.mobilePhone = [aDecoder decodeObjectForKey:kMovieTuesdayGoodModelMobilePhone];
    self.buyCount = [aDecoder decodeObjectForKey:kMovieTuesdayGoodModelBuyCount];
    self.tagMatch = [aDecoder decodeObjectForKey:kMovieTuesdayGoodModelTagMatch];
    self.movieTuesdayGoodModelIdentifier = [aDecoder decodeObjectForKey:kMovieTuesdayGoodModelId];
    self.weight = [aDecoder decodeObjectForKey:kMovieTuesdayGoodModelWeight];
    self.dealGoodsType = [aDecoder decodeObjectForKey:kMovieTuesdayGoodModelDealGoodsType];
    self.isNew = [aDecoder decodeObjectForKey:kMovieTuesdayGoodModelIsNew];
    self.balancePrice = [aDecoder decodeObjectForKey:kMovieTuesdayGoodModelBalancePrice];
    self.shopCateMatch = [aDecoder decodeObjectForKey:kMovieTuesdayGoodModelShopCateMatch];
    self.shopCateId = [aDecoder decodeObjectForKey:kMovieTuesdayGoodModelShopCateId];
    self.definePayment = [aDecoder decodeObjectForKey:kMovieTuesdayGoodModelDefinePayment];
    self.sort = [aDecoder decodeObjectForKey:kMovieTuesdayGoodModelSort];
    self.onSale = [aDecoder decodeObjectForKey:kMovieTuesdayGoodModelOnSale];
    self.notice = [aDecoder decodeObjectForKey:kMovieTuesdayGoodModelNotice];
    self.code = [aDecoder decodeObjectForKey:kMovieTuesdayGoodModelCode];
    self.autoOrder = [aDecoder decodeObjectForKey:kMovieTuesdayGoodModelAutoOrder];
    self.discuss = [aDecoder decodeObjectForKey:kMovieTuesdayGoodModelDiscuss];
    self.couponBeginTime = [aDecoder decodeObjectForKey:kMovieTuesdayGoodModelCouponBeginTime];
    self.forbidSms = [aDecoder decodeObjectForKey:kMovieTuesdayGoodModelForbidSms];
    self.isHot = [aDecoder decodeObjectForKey:kMovieTuesdayGoodModelIsHot];
    self.isDeposit = [aDecoder decodeObjectForKey:kMovieTuesdayGoodModelIsDeposit];
    self.userMaxBought = [aDecoder decodeObjectForKey:kMovieTuesdayGoodModelUserMaxBought];
    self.isDelivery = [aDecoder decodeObjectForKey:kMovieTuesdayGoodModelIsDelivery];
    self.sales = [aDecoder decodeObjectForKey:kMovieTuesdayGoodModelSales];
    self.name = [aDecoder decodeObjectForKey:kMovieTuesdayGoodModelName];
    self.nameMatchRow = [aDecoder decodeObjectForKey:kMovieTuesdayGoodModelNameMatchRow];
    self.isCoupon = [aDecoder decodeObjectForKey:kMovieTuesdayGoodModelIsCoupon];
    self.userMinBought = [aDecoder decodeObjectForKey:kMovieTuesdayGoodModelUserMinBought];
    self.locateMatchRow = [aDecoder decodeObjectForKey:kMovieTuesdayGoodModelLocateMatchRow];
    self.cateId = [aDecoder decodeObjectForKey:kMovieTuesdayGoodModelCateId];
    self.cartType = [aDecoder decodeObjectForKey:kMovieTuesdayGoodModelCartType];
    self.shopCateMatchRow = [aDecoder decodeObjectForKey:kMovieTuesdayGoodModelShopCateMatchRow];
    self.reopen = [aDecoder decodeObjectForKey:kMovieTuesdayGoodModelReopen];
    self.isDelete = [aDecoder decodeObjectForKey:kMovieTuesdayGoodModelIsDelete];
    self.isLottery = [aDecoder decodeObjectForKey:kMovieTuesdayGoodModelIsLottery];
    self.successTime = [aDecoder decodeObjectForKey:kMovieTuesdayGoodModelSuccessTime];
    self.expireRefund = [aDecoder decodeObjectForKey:kMovieTuesdayGoodModelExpireRefund];
    self.seoKeyword = [aDecoder decodeObjectForKey:kMovieTuesdayGoodModelSeoKeyword];
    self.isRefund = [aDecoder decodeObjectForKey:kMovieTuesdayGoodModelIsRefund];
    self.dealType = [aDecoder decodeObjectForKey:kMovieTuesdayGoodModelDealType];
    self.isHome = [aDecoder decodeObjectForKey:kMovieTuesdayGoodModelIsHome];
    self.allowPromote = [aDecoder decodeObjectForKey:kMovieTuesdayGoodModelAllowPromote];
    self.createTime = [aDecoder decodeObjectForKey:kMovieTuesdayGoodModelCreateTime];
    self.beginTime = [aDecoder decodeObjectForKey:kMovieTuesdayGoodModelBeginTime];
    self.updateTime = [aDecoder decodeObjectForKey:kMovieTuesdayGoodModelUpdateTime];
    self.timeStatus = [aDecoder decodeObjectForKey:kMovieTuesdayGoodModelTimeStatus];
    self.returnScore = [aDecoder decodeObjectForKey:kMovieTuesdayGoodModelReturnScore];
    self.dealCateMatchRow = [aDecoder decodeObjectForKey:kMovieTuesdayGoodModelDealCateMatchRow];
    self.discount = [aDecoder decodeObjectForKey:kMovieTuesdayGoodModelDiscount];
    self.seoTitle = [aDecoder decodeObjectForKey:kMovieTuesdayGoodModelSeoTitle];
    self.tagMatchRow = [aDecoder decodeObjectForKey:kMovieTuesdayGoodModelTagMatchRow];
    self.buyType = [aDecoder decodeObjectForKey:kMovieTuesdayGoodModelBuyType];
    self.isShop = [aDecoder decodeObjectForKey:kMovieTuesdayGoodModelIsShop];
    self.imgs = [aDecoder decodeObjectForKey:kMovieTuesdayGoodModelImgs];
    self.accountId = [aDecoder decodeObjectForKey:kMovieTuesdayGoodModelAccountId];
    self.img = [aDecoder decodeObjectForKey:kMovieTuesdayGoodModelImg];
    self.uname = [aDecoder decodeObjectForKey:kMovieTuesdayGoodModelUname];
    self.buyStatus = [aDecoder decodeObjectForKey:kMovieTuesdayGoodModelBuyStatus];
    self.cityId = [aDecoder decodeObjectForKey:kMovieTuesdayGoodModelCityId];
    self.brandId = [aDecoder decodeObjectForKey:kMovieTuesdayGoodModelBrandId];
    self.isEffect = [aDecoder decodeObjectForKey:kMovieTuesdayGoodModelIsEffect];
    self.locationId = [aDecoder decodeObjectForKey:kMovieTuesdayGoodModelLocationId];
    self.userCount = [aDecoder decodeObjectForKey:kMovieTuesdayGoodModelUserCount];
    self.ypoint = [aDecoder decodeObjectForKey:kMovieTuesdayGoodModelYpoint];
    self.brief = [aDecoder decodeObjectForKey:kMovieTuesdayGoodModelBrief];
    self.originPrice = [aDecoder decodeObjectForKey:kMovieTuesdayGoodModelOriginPrice];
    self.minBought = [aDecoder decodeObjectForKey:kMovieTuesdayGoodModelMinBought];
    self.isReferral = [aDecoder decodeObjectForKey:kMovieTuesdayGoodModelIsReferral];
    self.isBest = [aDecoder decodeObjectForKey:kMovieTuesdayGoodModelIsBest];
    self.deliveryId = [aDecoder decodeObjectForKey:kMovieTuesdayGoodModelDeliveryId];
    self.avgPoint = [aDecoder decodeObjectForKey:kMovieTuesdayGoodModelAvgPoint];
    self.attributes = [aDecoder decodeObjectForKey:kMovieTuesdayGoodModelAttributes];
    self.locationDealTypeId = [aDecoder decodeObjectForKey:kMovieTuesdayGoodModelLocationDealTypeId];
    self.endTime = [aDecoder decodeObjectForKey:kMovieTuesdayGoodModelEndTime];
    self.totalPoint = [aDecoder decodeObjectForKey:kMovieTuesdayGoodModelTotalPoint];
    self.weightId = [aDecoder decodeObjectForKey:kMovieTuesdayGoodModelWeightId];
    self.currentPrice = [aDecoder decodeObjectForKey:kMovieTuesdayGoodModelCurrentPrice];
    self.maxBought = [aDecoder decodeObjectForKey:kMovieTuesdayGoodModelMaxBought];
    self.supplierId = [aDecoder decodeObjectForKey:kMovieTuesdayGoodModelSupplierId];
    self.feature = [aDecoder decodeObjectForKey:kMovieTuesdayGoodModelFeature];
    self.locateMatch = [aDecoder decodeObjectForKey:kMovieTuesdayGoodModelLocateMatch];
    self.acreage = [aDecoder decodeObjectForKey:kMovieTuesdayGoodModelAcreage];
    self.time = [aDecoder decodeObjectForKey:kMovieTuesdayGoodModelTime];
    self.couponEndTime = [aDecoder decodeObjectForKey:kMovieTuesdayGoodModelCouponEndTime];
    self.freeDelivery = [aDecoder decodeObjectForKey:kMovieTuesdayGoodModelFreeDelivery];
    self.anyRefund = [aDecoder decodeObjectForKey:kMovieTuesdayGoodModelAnyRefund];
    self.xpoint = [aDecoder decodeObjectForKey:kMovieTuesdayGoodModelXpoint];
    self.seoDescription = [aDecoder decodeObjectForKey:kMovieTuesdayGoodModelSeoDescription];
    self.nameMatch = [aDecoder decodeObjectForKey:kMovieTuesdayGoodModelNameMatch];
    self.isRecommend = [aDecoder decodeObjectForKey:kMovieTuesdayGoodModelIsRecommend];
    self.depositPrice = [aDecoder decodeObjectForKey:kMovieTuesdayGoodModelDepositPrice];
    self.dealCateMatch = [aDecoder decodeObjectForKey:kMovieTuesdayGoodModelDealCateMatch];
    self.multiAttr = [aDecoder decodeObjectForKey:kMovieTuesdayGoodModelMultiAttr];
    self.brandPromote = [aDecoder decodeObjectForKey:kMovieTuesdayGoodModelBrandPromote];
    return self;
}

- (void)encodeWithCoder:(NSCoder *)aCoder
{

    [aCoder encodeObject:_returnMoney forKey:kMovieTuesdayGoodModelReturnMoney];
    [aCoder encodeObject:_publishWait forKey:kMovieTuesdayGoodModelPublishWait];
    [aCoder encodeObject:_movieTuesdayGoodModelDescription forKey:kMovieTuesdayGoodModelDescription];
    [aCoder encodeObject:_icon forKey:kMovieTuesdayGoodModelIcon];
    [aCoder encodeObject:_subName forKey:kMovieTuesdayGoodModelSubName];
    [aCoder encodeObject:_mobilePhone forKey:kMovieTuesdayGoodModelMobilePhone];
    [aCoder encodeObject:_buyCount forKey:kMovieTuesdayGoodModelBuyCount];
    [aCoder encodeObject:_tagMatch forKey:kMovieTuesdayGoodModelTagMatch];
    [aCoder encodeObject:_movieTuesdayGoodModelIdentifier forKey:kMovieTuesdayGoodModelId];
    [aCoder encodeObject:_weight forKey:kMovieTuesdayGoodModelWeight];
    [aCoder encodeObject:_dealGoodsType forKey:kMovieTuesdayGoodModelDealGoodsType];
    [aCoder encodeObject:_isNew forKey:kMovieTuesdayGoodModelIsNew];
    [aCoder encodeObject:_balancePrice forKey:kMovieTuesdayGoodModelBalancePrice];
    [aCoder encodeObject:_shopCateMatch forKey:kMovieTuesdayGoodModelShopCateMatch];
    [aCoder encodeObject:_shopCateId forKey:kMovieTuesdayGoodModelShopCateId];
    [aCoder encodeObject:_definePayment forKey:kMovieTuesdayGoodModelDefinePayment];
    [aCoder encodeObject:_sort forKey:kMovieTuesdayGoodModelSort];
    [aCoder encodeObject:_onSale forKey:kMovieTuesdayGoodModelOnSale];
    [aCoder encodeObject:_notice forKey:kMovieTuesdayGoodModelNotice];
    [aCoder encodeObject:_code forKey:kMovieTuesdayGoodModelCode];
    [aCoder encodeObject:_autoOrder forKey:kMovieTuesdayGoodModelAutoOrder];
    [aCoder encodeBool:_discuss forKey:kMovieTuesdayGoodModelDiscuss];
    [aCoder encodeObject:_couponBeginTime forKey:kMovieTuesdayGoodModelCouponBeginTime];
    [aCoder encodeObject:_forbidSms forKey:kMovieTuesdayGoodModelForbidSms];
    [aCoder encodeObject:_isHot forKey:kMovieTuesdayGoodModelIsHot];
    [aCoder encodeObject:_isDeposit forKey:kMovieTuesdayGoodModelIsDeposit];
    [aCoder encodeObject:_userMaxBought forKey:kMovieTuesdayGoodModelUserMaxBought];
    [aCoder encodeObject:_isDelivery forKey:kMovieTuesdayGoodModelIsDelivery];
    [aCoder encodeObject:_sales forKey:kMovieTuesdayGoodModelSales];
    [aCoder encodeObject:_name forKey:kMovieTuesdayGoodModelName];
    [aCoder encodeObject:_nameMatchRow forKey:kMovieTuesdayGoodModelNameMatchRow];
    [aCoder encodeObject:_isCoupon forKey:kMovieTuesdayGoodModelIsCoupon];
    [aCoder encodeObject:_userMinBought forKey:kMovieTuesdayGoodModelUserMinBought];
    [aCoder encodeObject:_locateMatchRow forKey:kMovieTuesdayGoodModelLocateMatchRow];
    [aCoder encodeObject:_cateId forKey:kMovieTuesdayGoodModelCateId];
    [aCoder encodeObject:_cartType forKey:kMovieTuesdayGoodModelCartType];
    [aCoder encodeObject:_shopCateMatchRow forKey:kMovieTuesdayGoodModelShopCateMatchRow];
    [aCoder encodeObject:_reopen forKey:kMovieTuesdayGoodModelReopen];
    [aCoder encodeObject:_isDelete forKey:kMovieTuesdayGoodModelIsDelete];
    [aCoder encodeObject:_isLottery forKey:kMovieTuesdayGoodModelIsLottery];
    [aCoder encodeObject:_successTime forKey:kMovieTuesdayGoodModelSuccessTime];
    [aCoder encodeObject:_expireRefund forKey:kMovieTuesdayGoodModelExpireRefund];
    [aCoder encodeObject:_seoKeyword forKey:kMovieTuesdayGoodModelSeoKeyword];
    [aCoder encodeObject:_isRefund forKey:kMovieTuesdayGoodModelIsRefund];
    [aCoder encodeObject:_dealType forKey:kMovieTuesdayGoodModelDealType];
    [aCoder encodeObject:_isHome forKey:kMovieTuesdayGoodModelIsHome];
    [aCoder encodeObject:_allowPromote forKey:kMovieTuesdayGoodModelAllowPromote];
    [aCoder encodeObject:_createTime forKey:kMovieTuesdayGoodModelCreateTime];
    [aCoder encodeObject:_beginTime forKey:kMovieTuesdayGoodModelBeginTime];
    [aCoder encodeObject:_updateTime forKey:kMovieTuesdayGoodModelUpdateTime];
    [aCoder encodeObject:_timeStatus forKey:kMovieTuesdayGoodModelTimeStatus];
    [aCoder encodeObject:_returnScore forKey:kMovieTuesdayGoodModelReturnScore];
    [aCoder encodeObject:_dealCateMatchRow forKey:kMovieTuesdayGoodModelDealCateMatchRow];
    [aCoder encodeObject:_discount forKey:kMovieTuesdayGoodModelDiscount];
    [aCoder encodeObject:_seoTitle forKey:kMovieTuesdayGoodModelSeoTitle];
    [aCoder encodeObject:_tagMatchRow forKey:kMovieTuesdayGoodModelTagMatchRow];
    [aCoder encodeObject:_buyType forKey:kMovieTuesdayGoodModelBuyType];
    [aCoder encodeObject:_isShop forKey:kMovieTuesdayGoodModelIsShop];
    [aCoder encodeBool:_imgs forKey:kMovieTuesdayGoodModelImgs];
    [aCoder encodeObject:_accountId forKey:kMovieTuesdayGoodModelAccountId];
    [aCoder encodeObject:_img forKey:kMovieTuesdayGoodModelImg];
    [aCoder encodeObject:_uname forKey:kMovieTuesdayGoodModelUname];
    [aCoder encodeObject:_buyStatus forKey:kMovieTuesdayGoodModelBuyStatus];
    [aCoder encodeObject:_cityId forKey:kMovieTuesdayGoodModelCityId];
    [aCoder encodeObject:_brandId forKey:kMovieTuesdayGoodModelBrandId];
    [aCoder encodeObject:_isEffect forKey:kMovieTuesdayGoodModelIsEffect];
    [aCoder encodeObject:_locationId forKey:kMovieTuesdayGoodModelLocationId];
    [aCoder encodeObject:_userCount forKey:kMovieTuesdayGoodModelUserCount];
    [aCoder encodeObject:_ypoint forKey:kMovieTuesdayGoodModelYpoint];
    [aCoder encodeObject:_brief forKey:kMovieTuesdayGoodModelBrief];
    [aCoder encodeObject:_originPrice forKey:kMovieTuesdayGoodModelOriginPrice];
    [aCoder encodeObject:_minBought forKey:kMovieTuesdayGoodModelMinBought];
    [aCoder encodeObject:_isReferral forKey:kMovieTuesdayGoodModelIsReferral];
    [aCoder encodeObject:_isBest forKey:kMovieTuesdayGoodModelIsBest];
    [aCoder encodeObject:_deliveryId forKey:kMovieTuesdayGoodModelDeliveryId];
    [aCoder encodeObject:_avgPoint forKey:kMovieTuesdayGoodModelAvgPoint];
    [aCoder encodeObject:_attributes forKey:kMovieTuesdayGoodModelAttributes];
    [aCoder encodeObject:_locationDealTypeId forKey:kMovieTuesdayGoodModelLocationDealTypeId];
    [aCoder encodeObject:_endTime forKey:kMovieTuesdayGoodModelEndTime];
    [aCoder encodeObject:_totalPoint forKey:kMovieTuesdayGoodModelTotalPoint];
    [aCoder encodeObject:_weightId forKey:kMovieTuesdayGoodModelWeightId];
    [aCoder encodeObject:_currentPrice forKey:kMovieTuesdayGoodModelCurrentPrice];
    [aCoder encodeObject:_maxBought forKey:kMovieTuesdayGoodModelMaxBought];
    [aCoder encodeObject:_supplierId forKey:kMovieTuesdayGoodModelSupplierId];
    [aCoder encodeObject:_feature forKey:kMovieTuesdayGoodModelFeature];
    [aCoder encodeObject:_locateMatch forKey:kMovieTuesdayGoodModelLocateMatch];
    [aCoder encodeObject:_acreage forKey:kMovieTuesdayGoodModelAcreage];
    [aCoder encodeObject:_time forKey:kMovieTuesdayGoodModelTime];
    [aCoder encodeObject:_couponEndTime forKey:kMovieTuesdayGoodModelCouponEndTime];
    [aCoder encodeObject:_freeDelivery forKey:kMovieTuesdayGoodModelFreeDelivery];
    [aCoder encodeObject:_anyRefund forKey:kMovieTuesdayGoodModelAnyRefund];
    [aCoder encodeObject:_xpoint forKey:kMovieTuesdayGoodModelXpoint];
    [aCoder encodeObject:_seoDescription forKey:kMovieTuesdayGoodModelSeoDescription];
    [aCoder encodeObject:_nameMatch forKey:kMovieTuesdayGoodModelNameMatch];
    [aCoder encodeObject:_isRecommend forKey:kMovieTuesdayGoodModelIsRecommend];
    [aCoder encodeObject:_depositPrice forKey:kMovieTuesdayGoodModelDepositPrice];
    [aCoder encodeObject:_dealCateMatch forKey:kMovieTuesdayGoodModelDealCateMatch];
    [aCoder encodeObject:_multiAttr forKey:kMovieTuesdayGoodModelMultiAttr];
    [aCoder encodeObject:_brandPromote forKey:kMovieTuesdayGoodModelBrandPromote];
}

- (id)copyWithZone:(NSZone *)zone
{
    MovieTuesdayGoodModel *copy = [[MovieTuesdayGoodModel alloc] init];
    
    if (copy) {

        copy.returnMoney = [self.returnMoney copyWithZone:zone];
        copy.publishWait = [self.publishWait copyWithZone:zone];
        copy.movieTuesdayGoodModelDescription = [self.movieTuesdayGoodModelDescription copyWithZone:zone];
        copy.icon = [self.icon copyWithZone:zone];
        copy.subName = [self.subName copyWithZone:zone];
        copy.mobilePhone = [self.mobilePhone copyWithZone:zone];
        copy.buyCount = [self.buyCount copyWithZone:zone];
        copy.tagMatch = [self.tagMatch copyWithZone:zone];
        copy.movieTuesdayGoodModelIdentifier = [self.movieTuesdayGoodModelIdentifier copyWithZone:zone];
        copy.weight = [self.weight copyWithZone:zone];
        copy.dealGoodsType = [self.dealGoodsType copyWithZone:zone];
        copy.isNew = [self.isNew copyWithZone:zone];
        copy.balancePrice = [self.balancePrice copyWithZone:zone];
        copy.shopCateMatch = [self.shopCateMatch copyWithZone:zone];
        copy.shopCateId = [self.shopCateId copyWithZone:zone];
        copy.definePayment = [self.definePayment copyWithZone:zone];
        copy.sort = [self.sort copyWithZone:zone];
        copy.onSale = [self.onSale copyWithZone:zone];
        copy.notice = [self.notice copyWithZone:zone];
        copy.code = [self.code copyWithZone:zone];
        copy.autoOrder = [self.autoOrder copyWithZone:zone];
        copy.discuss = self.discuss;
        copy.couponBeginTime = [self.couponBeginTime copyWithZone:zone];
        copy.forbidSms = [self.forbidSms copyWithZone:zone];
        copy.isHot = [self.isHot copyWithZone:zone];
        copy.isDeposit = [self.isDeposit copyWithZone:zone];
        copy.userMaxBought = [self.userMaxBought copyWithZone:zone];
        copy.isDelivery = [self.isDelivery copyWithZone:zone];
        copy.sales = [self.sales copyWithZone:zone];
        copy.name = [self.name copyWithZone:zone];
        copy.nameMatchRow = [self.nameMatchRow copyWithZone:zone];
        copy.isCoupon = [self.isCoupon copyWithZone:zone];
        copy.userMinBought = [self.userMinBought copyWithZone:zone];
        copy.locateMatchRow = [self.locateMatchRow copyWithZone:zone];
        copy.cateId = [self.cateId copyWithZone:zone];
        copy.cartType = [self.cartType copyWithZone:zone];
        copy.shopCateMatchRow = [self.shopCateMatchRow copyWithZone:zone];
        copy.reopen = [self.reopen copyWithZone:zone];
        copy.isDelete = [self.isDelete copyWithZone:zone];
        copy.isLottery = [self.isLottery copyWithZone:zone];
        copy.successTime = [self.successTime copyWithZone:zone];
        copy.expireRefund = [self.expireRefund copyWithZone:zone];
        copy.seoKeyword = [self.seoKeyword copyWithZone:zone];
        copy.isRefund = [self.isRefund copyWithZone:zone];
        copy.dealType = [self.dealType copyWithZone:zone];
        copy.isHome = [self.isHome copyWithZone:zone];
        copy.allowPromote = [self.allowPromote copyWithZone:zone];
        copy.createTime = [self.createTime copyWithZone:zone];
        copy.beginTime = [self.beginTime copyWithZone:zone];
        copy.updateTime = [self.updateTime copyWithZone:zone];
        copy.timeStatus = [self.timeStatus copyWithZone:zone];
        copy.returnScore = [self.returnScore copyWithZone:zone];
        copy.dealCateMatchRow = [self.dealCateMatchRow copyWithZone:zone];
        copy.discount = [self.discount copyWithZone:zone];
        copy.seoTitle = [self.seoTitle copyWithZone:zone];
        copy.tagMatchRow = [self.tagMatchRow copyWithZone:zone];
        copy.buyType = [self.buyType copyWithZone:zone];
        copy.isShop = [self.isShop copyWithZone:zone];
        copy.imgs = self.imgs;
        copy.accountId = [self.accountId copyWithZone:zone];
        copy.img = [self.img copyWithZone:zone];
        copy.uname = [self.uname copyWithZone:zone];
        copy.buyStatus = [self.buyStatus copyWithZone:zone];
        copy.cityId = [self.cityId copyWithZone:zone];
        copy.brandId = [self.brandId copyWithZone:zone];
        copy.isEffect = [self.isEffect copyWithZone:zone];
        copy.locationId = [self.locationId copyWithZone:zone];
        copy.userCount = [self.userCount copyWithZone:zone];
        copy.ypoint = [self.ypoint copyWithZone:zone];
        copy.brief = [self.brief copyWithZone:zone];
        copy.originPrice = [self.originPrice copyWithZone:zone];
        copy.minBought = [self.minBought copyWithZone:zone];
        copy.isReferral = [self.isReferral copyWithZone:zone];
        copy.isBest = [self.isBest copyWithZone:zone];
        copy.deliveryId = [self.deliveryId copyWithZone:zone];
        copy.avgPoint = [self.avgPoint copyWithZone:zone];
        copy.attributes = [self.attributes copyWithZone:zone];
        copy.locationDealTypeId = [self.locationDealTypeId copyWithZone:zone];
        copy.endTime = [self.endTime copyWithZone:zone];
        copy.totalPoint = [self.totalPoint copyWithZone:zone];
        copy.weightId = [self.weightId copyWithZone:zone];
        copy.currentPrice = [self.currentPrice copyWithZone:zone];
        copy.maxBought = [self.maxBought copyWithZone:zone];
        copy.supplierId = [self.supplierId copyWithZone:zone];
        copy.feature = [self.feature copyWithZone:zone];
        copy.locateMatch = [self.locateMatch copyWithZone:zone];
        copy.acreage = [self.acreage copyWithZone:zone];
        copy.time = [self.time copyWithZone:zone];
        copy.couponEndTime = [self.couponEndTime copyWithZone:zone];
        copy.freeDelivery = [self.freeDelivery copyWithZone:zone];
        copy.anyRefund = [self.anyRefund copyWithZone:zone];
        copy.xpoint = [self.xpoint copyWithZone:zone];
        copy.seoDescription = [self.seoDescription copyWithZone:zone];
        copy.nameMatch = [self.nameMatch copyWithZone:zone];
        copy.isRecommend = [self.isRecommend copyWithZone:zone];
        copy.depositPrice = [self.depositPrice copyWithZone:zone];
        copy.dealCateMatch = [self.dealCateMatch copyWithZone:zone];
        copy.multiAttr = [self.multiAttr copyWithZone:zone];
        copy.brandPromote = [self.brandPromote copyWithZone:zone];
    }
    
    return copy;
}


@end
